export const dynamic = "force-dynamic";

import Link from "next/link";
import { unstable_cache } from "next/cache";
import { ArrowDownRight, ArrowUpRight, Clock3 } from "lucide-react";

import { DashboardActivityChart } from "@/components/dashboard-activity-chart";
import { Footer } from "@/components/footer";
import { Navbar } from "@/components/navbar";
import type { SectionInfo } from "@/components/section-info-modal";
import { SectionHeader } from "@/components/section-header";
import { GlassPanel } from "@/components/ui/glass-panel";
import { getBotDashboardData } from "@/lib/bot-dashboard-data";
import { getStrategySummaries } from "@/lib/strategy-artifacts";
import { cn } from "@/lib/utils";

const getCachedDashboardData = unstable_cache(
  async () => {
    const [botData, strategies] = await Promise.all([
      getBotDashboardData(),
      getStrategySummaries(),
    ]);

    return {
      botData,
      strategies,
    };
  },
  ["dashboard-single-page-data"],
  { revalidate: 60 }
);

function formatPercent(value: number | null) {
  if (value == null) {
    return "—";
  }
  return `${value.toFixed(1)}%`;
}

function formatCurrency(value: number | null) {
  if (value == null) {
    return "—";
  }
  return `${value < 0 ? "-" : ""}$${Math.abs(value).toFixed(2)}`;
}

function formatTimestamp(value: string | null) {
  if (!value) {
    return "Unknown";
  }

  return new Date(value).toLocaleString("en-US", {
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    timeZone: "UTC",
  });
}

function formatMarketType(value: string) {
  const [asset, interval] = value.split("_");
  if (!asset || !interval) {
    return value;
  }
  return `${asset.toUpperCase()} ${interval}`;
}

function formatTradePrice(value: number | null) {
  if (value == null) {
    return "—";
  }
  if (value <= 1) {
    return `${(value * 100).toFixed(1)}¢`;
  }
  return `$${value.toFixed(2)}`;
}

function metricToneClass(tone: "positive" | "negative" | "neutral") {
  if (tone === "positive") {
    return "text-emerald-400";
  }
  if (tone === "negative") {
    return "text-red-400";
  }
  return "text-zinc-100";
}

const STRATEGY_METRIC_EXPLANATIONS: Record<string, string> = {
  total_pnl: "Net profit or loss generated by the latest strategy result after all modeled trades.",
  roi: "Return on invested capital for the latest strategy result, shown as a percentage.",
  win_rate: "Share of tested trades that finished profitable in the latest result set.",
  profit_factor: "Gross profit divided by gross loss. Values above 1.00 mean profits outweigh losses.",
  sharpe_ratio: "Risk-adjusted return that compares average excess return against volatility.",
  sortino_ratio: "Risk-adjusted return that penalizes downside volatility more than upside volatility.",
  max_drawdown: "Largest peak-to-trough equity decline observed in the result set.",
  total_bets: "Number of trades evaluated for that strategy result.",
  trades_taken: "Number of trades evaluated for that strategy result.",
  expected_value: "Average expected P&L contribution per trade in the latest result.",
  avg_bet_pnl: "Average profit or loss per trade in the latest result.",
  avg_pnl_per_trade: "Average profit or loss per trade in the latest result.",
  consistency_score: "Stability score from the artifact showing how evenly performance held across slices.",
  pct_profitable_assets: "Percentage of asset slices that stayed profitable in the latest validation result.",
  pct_profitable_durations: "Percentage of duration slices that stayed profitable in the latest validation result.",
};

function getStrategyMetricExplanation(key: string, label: string) {
  return STRATEGY_METRIC_EXPLANATIONS[key] ?? `${label} is shown because it is one of the strongest metrics available in the latest artifact for that strategy.`;
}

function buildStrategyResultsInfo(strategies: Awaited<ReturnType<typeof getStrategySummaries>>): SectionInfo {
  const metricBullets = new Map<string, string>();

  for (const strategy of strategies) {
    for (const metric of strategy.summaryMetrics.slice(0, 5)) {
      if (!metricBullets.has(metric.key)) {
        metricBullets.set(metric.key, `${metric.label} - ${getStrategyMetricExplanation(metric.key, metric.label)}`);
      }
    }
  }

  return {
    title: "Strategy Results",
    sections: [
      {
        heading: "What is this?",
        content:
          "Each card is generated from the newest strategy artifacts found in the repo. The dashboard does not force a fixed schema and instead surfaces the strongest metrics available for each strategy.",
      },
      {
        heading: "Metrics shown on the cards",
        content:
          "Every metric currently visible on the strategy cards is explained below. This list updates from the live strategy summaries used to render the dashboard.",
        bullets: [...metricBullets.values()],
      },
    ],
  };
}

export default async function DashboardPage() {
  const { botData, strategies } = await getCachedDashboardData();

  const overall = botData.overall;
  const last24Hours = botData.last24Hours;
  const previous24Hours = botData.previous24Hours;
  const strategyResultsInfo = buildStrategyResultsInfo(strategies);

  const overallTakeProfitRate =
    overall && overall.takeProfits + overall.heldToExpiryLosses + overall.stopLosses > 0
      ? (overall.takeProfits / (overall.takeProfits + overall.heldToExpiryLosses + overall.stopLosses)) * 100
      : null;

  const last24TakeProfitRate =
    last24Hours && last24Hours.takeProfits + last24Hours.heldToExpiryLosses + last24Hours.stopLosses > 0
      ? (last24Hours.takeProfits / (last24Hours.takeProfits + last24Hours.heldToExpiryLosses + last24Hours.stopLosses)) * 100
      : null;

  const pnlDelta24h =
    last24Hours && previous24Hours
      ? last24Hours.totalPnl - previous24Hours.totalPnl
      : null;

  return (
    <div className="min-h-screen flex flex-col overflow-x-hidden">
      <Navbar />

      <main className="mx-auto w-full max-w-7xl flex-1 px-4 py-6 md:px-6 md:py-10">
        <header className="mb-8 rounded-3xl border border-zinc-800/60 bg-zinc-950/80 p-6 backdrop-blur-xl md:mb-10 md:p-8">
          <div className="max-w-3xl">
            <div>
              <p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary/70">
                PolyEdge Dashboard
              </p>
              <h1 className="mt-3 text-3xl font-semibold tracking-tight text-zinc-50 md:text-4xl">
                One view for live bot health and strategy results.
              </h1>
            </div>
          </div>
        </header>

        <section id="bot-overview" className="scroll-mt-24">
          <SectionHeader title="Bot Overview" />

          {botData.connected && overall ? (
            <div className="space-y-5">
              <div className="grid gap-5 xl:grid-cols-[1.15fr_0.85fr]">
                <GlassPanel variant="glow-wide" className="h-full">
                  <div className="flex h-full flex-col p-6 md:p-7">
                    <div className="flex flex-wrap items-center gap-2">
                      <span className="rounded-full border border-emerald-500/20 bg-emerald-500/10 px-3 py-1 text-xs font-semibold uppercase tracking-[0.18em] text-emerald-400">
                        Live bot data
                      </span>
                      <span className="rounded-full border border-zinc-800 bg-zinc-900/80 px-3 py-1 text-xs font-medium text-zinc-400">
                        Last trade {formatTimestamp(overall.lastTradeAt)}
                      </span>
                    </div>

                    <div className="mt-6 grid gap-4 lg:grid-cols-[1.05fr_0.95fr]">
                      <div className="rounded-3xl border border-zinc-800/70 bg-zinc-900/55 p-5">
                        <p className="text-sm text-zinc-400">Net realized P&amp;L</p>
                        <p
                          className={cn(
                            "mt-2 font-mono text-4xl font-bold tracking-tight",
                            overall.totalPnl > 0
                              ? "text-emerald-400"
                              : overall.totalPnl < 0
                                ? "text-red-400"
                                : "text-zinc-100"
                          )}
                        >
                          {formatCurrency(overall.totalPnl)}
                        </p>
                        <p className="mt-3 text-sm leading-7 text-zinc-300">
                          {overallTakeProfitRate == null
                            ? "No resolved trades yet."
                            : `${formatPercent(overallTakeProfitRate)} take-profit exits across ${overall.resolvedTrades.toLocaleString(
                                "en-US"
                              )} resolved trades.`}
                        </p>

                        <div className="mt-5 grid grid-cols-3 gap-3">
                          {[
                            {
                              label: "Take Profit",
                              value: overall.takeProfits.toLocaleString("en-US"),
                              tone: "text-emerald-400",
                            },
                            {
                              label: "Stop Loss",
                              value: overall.stopLosses.toLocaleString("en-US"),
                              tone: "text-amber-400",
                            },
                            {
                              label: "Held to Expiry",
                              value: overall.heldToExpiryLosses.toLocaleString("en-US"),
                              tone: "text-red-400",
                            },
                          ].map((item) => (
                            <div key={item.label} className="rounded-2xl border border-zinc-800/70 bg-zinc-950/70 p-3">
                              <p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-zinc-500">
                                {item.label}
                              </p>
                              <p className={cn("mt-2 font-mono text-lg", item.tone)}>{item.value}</p>
                            </div>
                          ))}
                        </div>
                      </div>

                      <div className="grid gap-3 sm:grid-cols-2">
                        {[
                          {
                            label: "Profit Factor",
                            value: overall.profitFactor == null ? "—" : overall.profitFactor.toFixed(2),
                          },
                          {
                            label: "Avg Trade",
                            value: formatCurrency(overall.avgPnlPerTrade),
                          },
                          {
                            label: "Resolved Trades",
                            value: overall.resolvedTrades.toLocaleString("en-US"),
                          },
                          {
                            label: "Open Trades",
                            value: overall.openTrades.toLocaleString("en-US"),
                          },
                        ].map((item) => (
                          <div key={item.label} className="rounded-2xl border border-zinc-800/70 bg-zinc-900/70 p-4">
                            <p className="text-xs font-semibold uppercase tracking-[0.14em] text-zinc-500">
                              {item.label}
                            </p>
                            <p className="mt-2 font-mono text-xl text-zinc-100">{item.value}</p>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                </GlassPanel>

                <GlassPanel variant="subtle">
                  <div className="p-6 md:p-7">
                    <div className="flex items-center justify-between gap-3">
                      <div>
                        <p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary/70">
                          Last 24 Hours
                        </p>
                      </div>
                      {pnlDelta24h != null && (
                        <div
                          className={cn(
                            "rounded-full px-3 py-1 text-xs font-semibold",
                            pnlDelta24h >= 0
                              ? "bg-emerald-500/10 text-emerald-400"
                              : "bg-red-500/10 text-red-400"
                          )}
                        >
                          {pnlDelta24h >= 0 ? "+" : ""}
                          {formatCurrency(pnlDelta24h)} vs prior 24h
                        </div>
                      )}
                    </div>

                    <div className="mt-5 grid grid-cols-2 gap-3">
                      {[
                        {
                          label: "P&L",
                          value: formatCurrency(last24Hours?.totalPnl ?? null),
                          tone:
                            (last24Hours?.totalPnl ?? 0) > 0
                              ? "text-emerald-400"
                              : (last24Hours?.totalPnl ?? 0) < 0
                                ? "text-red-400"
                                : "text-zinc-100",
                        },
                        {
                          label: "Take Profit",
                          value: last24Hours?.takeProfits.toLocaleString("en-US") ?? "0",
                          tone: "text-emerald-400",
                        },
                        {
                          label: "Stop Loss",
                          value: last24Hours?.stopLosses.toLocaleString("en-US") ?? "0",
                          tone: "text-amber-400",
                        },
                        {
                          label: "TP Rate",
                          value: formatPercent(last24TakeProfitRate),
                          tone: "text-zinc-100",
                        },
                      ].map((item) => (
                        <div key={item.label} className="rounded-2xl border border-zinc-800/70 bg-zinc-900/70 p-4">
                          <p className="text-xs font-semibold uppercase tracking-[0.14em] text-zinc-500">
                            {item.label}
                          </p>
                          <p className={cn("mt-2 font-mono text-xl", item.tone)}>{item.value}</p>
                        </div>
                      ))}
                    </div>

                    <p className="mt-4 text-sm leading-7 text-zinc-400">
                      {last24Hours && last24Hours.trades > 0
                        ? `${last24Hours.trades.toLocaleString("en-US")} resolved trades in the last 24 hours with an average of ${formatCurrency(
                            last24Hours.avgPnlPerTrade
                          )} per trade.`
                        : "No resolved trades in the last 24 hours yet."}
                    </p>

                    <div className="mt-5">
                      <DashboardActivityChart data={botData.activity24Hours} />
                    </div>
                  </div>
                </GlassPanel>
              </div>
            </div>
          ) : (
            <GlassPanel variant="subtle">
              <div className="p-6 md:p-7">
                <p className="text-sm font-semibold uppercase tracking-[0.16em] text-primary/70">
                  Live bot data unavailable
                </p>
                <p className="mt-3 max-w-2xl text-sm leading-7 text-zinc-400">
                  {botData.error ??
                    "The dashboard could not reach the trade database right now, so the live bot overview is hidden instead of blocking the page."}
                </p>
              </div>
            </GlassPanel>
          )}
        </section>

        <section id="strategy-results" className="mt-10 scroll-mt-24">
          <SectionHeader title="Strategy Results" info={strategyResultsInfo} />

          {strategies.length > 0 ? (
            <div className="grid items-stretch gap-5 md:grid-cols-2 xl:grid-cols-3">
              {strategies.map((strategy) => (
                <GlassPanel key={strategy.strategyId} variant="subtle" className="h-full">
                  <div className="flex h-full flex-col p-5">
                    <div className="flex items-start justify-between gap-3">
                      <div>
                        <div className="flex flex-wrap items-center gap-2">
                          <span className="rounded-full border border-primary/25 bg-primary/10 px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.18em] text-primary">
                            {strategy.strategyId}
                          </span>
                          <span className="rounded-full border border-zinc-800 bg-zinc-900/70 px-3 py-1 text-[11px] font-medium text-zinc-400">
                            {strategy.statusLabel}
                          </span>
                        </div>
                        <h3 className="mt-4 text-xl font-semibold tracking-tight text-zinc-50">
                          {strategy.displayName}
                        </h3>
                        <p className="mt-2 flex items-center gap-2 text-xs text-zinc-500">
                          <Clock3 className="h-3.5 w-3.5" />
                          {formatTimestamp(strategy.lastUpdatedAt)}
                        </p>
                      </div>

                      {strategy.primaryMetric && (
                        <div className="text-right">
                          <p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-zinc-500">
                            {strategy.primaryMetric.label}
                          </p>
                          <p className={cn("mt-2 font-mono text-2xl font-bold", metricToneClass(strategy.primaryMetric.tone))}>
                            {strategy.primaryMetric.displayValue}
                          </p>
                        </div>
                      )}
                    </div>

                    <div className="mt-5 grid grid-cols-2 gap-3">
                      {strategy.summaryMetrics.slice(1, 5).map((metric) => (
                        <div key={metric.key} className="rounded-2xl border border-zinc-800/70 bg-zinc-900/70 p-3">
                          <p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-zinc-500">
                            {metric.label}
                          </p>
                          <p className={cn("mt-2 font-mono text-lg", metricToneClass(metric.tone))}>
                            {metric.displayValue}
                          </p>
                        </div>
                      ))}
                    </div>

                    <div className="mt-auto pt-5">
                      <Link
                        href={strategy.route}
                        className="inline-flex items-center gap-2 rounded-full border border-zinc-800 bg-zinc-900/80 px-4 py-2 text-sm font-medium text-zinc-200 transition-colors hover:border-primary/35 hover:text-primary"
                      >
                        Open detail
                        <ArrowUpRight className="h-4 w-4" />
                      </Link>
                    </div>
                  </div>
                </GlassPanel>
              ))}
            </div>
          ) : (
            <GlassPanel variant="subtle">
              <div className="p-6 md:p-7">
                <p className="text-sm leading-7 text-zinc-400">
                  No strategy optimization artifacts were found in the current results folders.
                </p>
              </div>
            </GlassPanel>
          )}
        </section>

        <section id="trade-history" className="mt-10 scroll-mt-24">
          <SectionHeader title="Trade History" />

          <GlassPanel variant="glow-wide">
            <div className="overflow-x-auto">
              {botData.recentTrades.length > 0 ? (
                <div className="min-w-[900px]">
                  <table className="w-full table-fixed">
                    <thead className="bg-zinc-950">
                      <tr className="border-b border-zinc-800/40">
                        <th className="w-44 px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider text-zinc-500">
                          Date / Time
                        </th>
                        <th className="w-24 px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider text-zinc-500">
                          Symbol / Pair
                        </th>
                        <th className="w-36 px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider text-zinc-500">
                          Strategy
                        </th>
                        <th className="w-20 px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider text-zinc-500">
                          Side
                        </th>
                        <th className="w-24 px-4 py-3 text-right text-xs font-semibold uppercase tracking-wider text-zinc-500">
                          Entry Price
                        </th>
                        <th className="w-24 px-4 py-3 text-right text-xs font-semibold uppercase tracking-wider text-zinc-500">
                          Exit Price
                        </th>
                        <th className="w-24 px-4 py-3 text-right text-xs font-semibold uppercase tracking-wider text-zinc-500">
                          P&amp;L
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                    {botData.recentTrades.map((trade) => (
                      <tr
                        key={trade.id}
                        className="border-b border-zinc-800/20 transition-colors hover:bg-zinc-800/20 even:bg-zinc-900/30"
                      >
                        <td className="px-4 py-3 text-sm text-zinc-300">
                          <div className="font-medium text-zinc-100">{formatTimestamp(trade.placedAt)}</div>
                          <div className="text-xs text-zinc-500">
                            {trade.resolvedAt ? `Resolved ${formatTimestamp(trade.resolvedAt)}` : "Open"}
                          </div>
                        </td>
                        <td className="px-4 py-3 text-sm text-zinc-300">
                          {formatMarketType(trade.marketType)}
                        </td>
                        <td className="px-4 py-3">
                          <span className="inline-flex max-w-full truncate rounded-md border border-primary/20 bg-primary/10 px-2 py-0.5 text-xs font-medium text-primary">
                            {trade.strategyName}
                          </span>
                        </td>
                        <td className="px-4 py-3">
                          <span
                            className={cn(
                              "inline-flex items-center gap-1 text-sm",
                              trade.side.toLowerCase() === "up" ? "text-emerald-400" : "text-red-400"
                            )}
                          >
                            {trade.side.toLowerCase() === "up" ? (
                              <ArrowUpRight className="h-3.5 w-3.5" />
                            ) : (
                              <ArrowDownRight className="h-3.5 w-3.5" />
                            )}
                            {trade.side}
                          </span>
                        </td>
                        <td className="px-4 py-3 text-right font-mono text-sm tabular-nums text-zinc-200">
                          {formatTradePrice(trade.entryPrice)}
                        </td>
                        <td className="px-4 py-3 text-right font-mono text-sm tabular-nums text-zinc-200">
                          {trade.exitPrice == null ? "Open" : formatTradePrice(trade.exitPrice)}
                        </td>
                        <td
                          className={cn(
                            "px-4 py-3 text-right font-mono text-sm font-semibold tabular-nums",
                            trade.pnl == null
                              ? "text-zinc-500"
                              : trade.pnl > 0
                                ? "text-emerald-400"
                                : trade.pnl < 0
                                  ? "text-red-400"
                                  : "text-zinc-100"
                          )}
                        >
                          {trade.pnl == null ? "—" : formatCurrency(trade.pnl)}
                        </td>
                      </tr>
                    ))}
                    </tbody>
                  </table>
                </div>
              ) : (
                <div className="p-6 text-sm leading-7 text-zinc-400">
                  {botData.connected
                    ? "No recent trades are available yet."
                    : "Trade history is hidden because the live trade database is currently unavailable."}
                </div>
              )}
            </div>
          </GlassPanel>
        </section>
      </main>

      <Footer />
    </div>
  );
}
