[CmdletBinding()]
param(
    [string]$AdminUser = "postgres",
    [string]$AdminEnvPath,
    [string]$OutputEnvPath,
    [string]$ReadOnlyUser = "codex_ro",
    [string]$AppOwner = "polymarket"
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

. (Join-Path $PSScriptRoot "lib.ps1")

if (-not $AdminEnvPath) {
    $AdminEnvPath = Get-CodexDbDefaultEnvPath -Mode "write"
}
if (-not $OutputEnvPath) {
    $OutputEnvPath = Get-CodexDbDefaultEnvPath -Mode "read"
}

$adminConfig = Get-CodexDbConfig -Mode "write" -EnvPath $AdminEnvPath
$psqlPath = Get-PsqlPath

$bytes = New-Object byte[] 24
[System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
$readOnlyPassword = [Convert]::ToBase64String($bytes).TrimEnd("=").Replace("+", "A").Replace("/", "b")

function Quote-SqlLiteral {
    param([Parameter(Mandatory = $true)][string]$Value)
    return "'" + $Value.Replace("'", "''") + "'"
}

function Quote-SqlIdentifier {
    param([Parameter(Mandatory = $true)][string]$Value)
    return '"' + $Value.Replace('"', '""') + '"'
}

$readOnlyUserLiteral = Quote-SqlLiteral -Value $ReadOnlyUser
$readOnlyUserIdentifier = Quote-SqlIdentifier -Value $ReadOnlyUser
$readOnlyPasswordLiteral = Quote-SqlLiteral -Value $readOnlyPassword
$databaseIdentifier = Quote-SqlIdentifier -Value $adminConfig.Database
$appOwnerIdentifier = Quote-SqlIdentifier -Value $AppOwner

$sqlText = @"
DO `$guard`$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_roles
        WHERE rolname = current_user
          AND (rolsuper OR rolcreaterole)
    ) THEN
        RAISE EXCEPTION 'bootstrap-readonly-role requires a PostgreSQL role with CREATEROLE or SUPERUSER; current role % does not have it', current_user;
    END IF;
END
`$guard`$;

DO `$bootstrap`$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = $readOnlyUserLiteral) THEN
        EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L', $readOnlyUserLiteral, $readOnlyPasswordLiteral);
    ELSE
        EXECUTE format('ALTER ROLE %I LOGIN PASSWORD %L', $readOnlyUserLiteral, $readOnlyPasswordLiteral);
    END IF;
END
`$bootstrap`$;

GRANT CONNECT ON DATABASE $databaseIdentifier TO $readOnlyUserIdentifier;
GRANT USAGE ON SCHEMA public TO $readOnlyUserIdentifier;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO $readOnlyUserIdentifier;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO $readOnlyUserIdentifier;
ALTER DEFAULT PRIVILEGES FOR ROLE $appOwnerIdentifier IN SCHEMA public
    GRANT SELECT ON TABLES TO $readOnlyUserIdentifier;
ALTER DEFAULT PRIVILEGES FOR ROLE $appOwnerIdentifier IN SCHEMA public
    GRANT SELECT ON SEQUENCES TO $readOnlyUserIdentifier;
"@

$stateDir = Get-CodexDbStateDir
$sqlPath = Join-Path $stateDir ("bootstrap-ro-" + [guid]::NewGuid().ToString("N") + ".sql")
[System.IO.File]::WriteAllText($sqlPath, $sqlText, (Get-CodexDbUtf8NoBomEncoding))

$previousPassword = $env:PGPASSWORD

try {
    Remove-Item Env:PGPASSWORD -ErrorAction SilentlyContinue
    $args = @(
        "-X"
        "-W"
        "-v", "ON_ERROR_STOP=1"
        "-h", $adminConfig.Host
        "-p", $adminConfig.Port
        "-U", $AdminUser
        "-d", $adminConfig.Database
        "-f", $sqlPath
    )

    & $psqlPath @args
    if ($LASTEXITCODE -ne 0) {
        throw "Role bootstrap failed with exit code $LASTEXITCODE."
    }
} finally {
    if ($null -eq $previousPassword) {
        Remove-Item Env:PGPASSWORD -ErrorAction SilentlyContinue
    } else {
        $env:PGPASSWORD = $previousPassword
    }

    if (Test-Path $sqlPath) {
        Remove-Item $sqlPath -Force -ErrorAction SilentlyContinue
    }
}

$envText = @(
    "# Local ignored read-only credential file for Codex DB access"
    "# Generated by ops/codex-db/bootstrap-readonly-role.ps1"
    "POSTGRES_HOST=$($adminConfig.Host)"
    "POSTGRES_PORT=$($adminConfig.Port)"
    "POSTGRES_USER=$ReadOnlyUser"
    "POSTGRES_PASSWORD=$readOnlyPassword"
    "POSTGRES_DB=$($adminConfig.Database)"
) -join [Environment]::NewLine

[System.IO.File]::WriteAllText($OutputEnvPath, $envText + [Environment]::NewLine, (Get-CodexDbUtf8NoBomEncoding))

Write-Output "Read-only role bootstrap completed."
Write-Output "Wrote local credentials to $OutputEnvPath"
