"""Unified strategy report — same schema for backtest and live trading.

Both ``analysis.backtest_strategies`` and the trading bot produce
:class:`StrategyReport` instances with identical fields, enabling
side-by-side comparison by agents or humans.

Usage::

    from shared.strategies.report import StrategyReport

    # Create from metrics dict (backtest)
    report = StrategyReport.from_metrics(metrics, trades, context="backtest", ...)

    # Serialize
    report.to_json("reports/backtest/S1.json")
    report.to_markdown("reports/backtest/S1.md")

    # Load back
    loaded = StrategyReport.from_json("reports/backtest/S1.json")
"""

from __future__ import annotations

import json
import os
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Any


@dataclass
class TradeRecord:
    """Individual trade in a report — minimal fields for agent analysis."""

    market_id: str
    direction: str  # 'Up' or 'Down'
    entry_price: float
    exit_price: float  # 1.0/0.0 for resolution; actual price for early exit
    outcome: str  # 'win' or 'loss'
    pnl: float
    second_entered: int = 0
    asset: str = ""
    duration_minutes: int = 0
    exit_reason: str = "resolution"
    gross_pnl: float = 0.0
    entry_fee_usdc: float = 0.0
    exit_fee_usdc: float = 0.0
    net_shares: float = 1.0


@dataclass
class StrategyReport:
    """Unified strategy report produced by both backtest and live trading.

    All monetary values are in USD.  All rates/percentages are 0–100 scale.

    The ``context`` field distinguishes backtest from live:
      - ``"backtest"`` — generated by ``analysis.backtest_strategies``
      - ``"live"`` — generated by ``trading.report``

    ``generated_at`` is always UTC ISO-8601.
    """

    # ── Identity ────────────────────────────────────────────────────
    strategy_id: str  # 'S1', 'S2', etc.
    strategy_name: str  # 'S1_spike_reversion'
    context: str  # 'backtest' or 'live'
    generated_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    # ── Data scope ──────────────────────────────────────────────────
    date_range_start: str = ""  # ISO-8601 or empty
    date_range_end: str = ""
    total_markets_evaluated: int = 0
    skipped_markets_missing_features: int = 0

    # ── Core metrics (match engine.compute_metrics output) ──────────
    total_bets: int = 0
    wins: int = 0
    losses: int = 0
    win_rate_pct: float = 0.0
    total_pnl: float = 0.0
    avg_bet_pnl: float = 0.0
    profit_factor: float = 0.0
    expected_value: float = 0.0
    total_entry_fees: float = 0.0
    total_exit_fees: float = 0.0
    total_fees: float = 0.0

    # ── Risk metrics ────────────────────────────────────────────────
    sharpe_ratio: float = 0.0
    sortino_ratio: float = 0.0
    max_drawdown: float = 0.0
    std_dev_pnl: float = 0.0

    # ── Robustness ──────────────────────────────────────────────────
    pct_profitable_assets: float = 0.0
    pct_profitable_durations: float = 0.0
    consistency_score: float = 0.0

    # ── Quarterly PnL ──────────────────────────────────────────────
    q1_pnl: float = 0.0
    q2_pnl: float = 0.0
    q3_pnl: float = 0.0
    q4_pnl: float = 0.0

    # ── Composite ranking ──────────────────────────────────────────
    ranking_score: float = 0.0

    # ── Trade log (optional, for drill-down) ────────────────────────
    trades: list[dict[str, Any]] = field(default_factory=list)

    # ── Config snapshot ─────────────────────────────────────────────
    config: dict[str, Any] = field(default_factory=dict)

    # ── Serialization ───────────────────────────────────────────────

    def to_dict(self) -> dict[str, Any]:
        """Convert to plain dict (JSON-serializable)."""
        return asdict(self)

    def to_json(self, path: str) -> None:
        """Write report as JSON file."""
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            json.dump(self.to_dict(), f, indent=2, default=str)

    def to_markdown(self, path: str) -> None:
        """Write report as Markdown file for human consumption."""
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(self._render_markdown())

    def _render_markdown(self) -> str:
        ctx_label = "Backtest" if self.context == "backtest" else "Live Trading"
        lines = [
            f"# {self.strategy_id}: {self.strategy_name} — {ctx_label} Report\n",
            f"**Generated:** {self.generated_at}  ",
            f"**Context:** {self.context}  ",
        ]
        if self.date_range_start:
            lines.append(
                f"**Date range:** {self.date_range_start} → {self.date_range_end}  "
            )
        if self.total_markets_evaluated:
            lines.append(f"**Markets evaluated:** {self.total_markets_evaluated}  ")
        if self.skipped_markets_missing_features:
            lines.append(
                f"**Markets skipped (missing features):** {self.skipped_markets_missing_features}  "
            )
        lines.append("")

        # Performance summary table
        lines.append("## Performance Summary\n")
        lines.append("| Metric | Value |")
        lines.append("|--------|------:|")
        lines.append(f"| Total bets | {self.total_bets} |")
        lines.append(f"| Wins | {self.wins} |")
        lines.append(f"| Losses | {self.losses} |")
        lines.append(f"| Win rate | {self.win_rate_pct:.2f}% |")
        lines.append(f"| Total PnL | ${self.total_pnl:.4f} |")
        lines.append(f"| Avg bet PnL | ${self.avg_bet_pnl:.6f} |")
        lines.append(f"| Profit factor | {self.profit_factor:.4f} |")
        lines.append(f"| Expected value | ${self.expected_value:.6f} |")
        lines.append(f"| Entry fees | ${self.total_entry_fees:.6f} |")
        lines.append(f"| Exit fees | ${self.total_exit_fees:.6f} |")
        lines.append(f"| Total fees | ${self.total_fees:.6f} |")
        lines.append("")

        # Risk metrics
        lines.append("## Risk Metrics\n")
        lines.append("| Metric | Value |")
        lines.append("|--------|------:|")
        lines.append(f"| Sharpe ratio | {self.sharpe_ratio:.4f} |")
        lines.append(f"| Sortino ratio | {self.sortino_ratio:.4f} |")
        lines.append(f"| Max drawdown | ${self.max_drawdown:.4f} |")
        lines.append(f"| Std dev PnL | ${self.std_dev_pnl:.6f} |")
        lines.append("")

        # Robustness
        lines.append("## Robustness\n")
        lines.append("| Metric | Value |")
        lines.append("|--------|------:|")
        lines.append(
            f"| Profitable assets | {self.pct_profitable_assets:.1f}% |"
        )
        lines.append(
            f"| Profitable durations | {self.pct_profitable_durations:.1f}% |"
        )
        lines.append(f"| Consistency score | {self.consistency_score:.2f} |")
        lines.append("")

        # Quarterly
        lines.append("## Quarterly PnL\n")
        lines.append("| Quarter | PnL |")
        lines.append("|---------|----:|")
        lines.append(f"| Q1 | ${self.q1_pnl:.4f} |")
        lines.append(f"| Q2 | ${self.q2_pnl:.4f} |")
        lines.append(f"| Q3 | ${self.q3_pnl:.4f} |")
        lines.append(f"| Q4 | ${self.q4_pnl:.4f} |")
        lines.append("")

        # Ranking
        lines.append(f"## Ranking Score: {self.ranking_score:.2f}\n")

        # Config
        if self.config:
            lines.append("## Strategy Config\n")
            lines.append("```json")
            lines.append(json.dumps(self.config, indent=2, default=str))
            lines.append("```\n")

        # Trade summary
        if self.trades:
            lines.append(f"## Trades ({len(self.trades)} total)\n")
            lines.append(
                "| # | Market | Direction | Entry | Exit | Outcome | PnL |"
            )
            lines.append(
                "|---|--------|-----------|------:|-----:|---------|----:|"
            )
            for i, t in enumerate(self.trades[:50], 1):
                mid = t.get("market_id", "")[:16]
                lines.append(
                    f"| {i} | {mid}… | {t.get('direction', '')} | "
                    f"${t.get('entry_price', 0):.4f} | "
                    f"${t.get('exit_price', 0):.4f} | "
                    f"{t.get('outcome', '')} | "
                    f"${t.get('pnl', 0):+.4f} |"
                )
            if len(self.trades) > 50:
                lines.append(
                    f"\n*Showing first 50 of {len(self.trades)} trades.*\n"
                )

        return "\n".join(lines) + "\n"

    # ── Deserialization ─────────────────────────────────────────────

    @classmethod
    def from_json(cls, path: str) -> StrategyReport:
        """Load a report from a JSON file."""
        with open(path) as f:
            data = json.load(f)
        # Pop trade list to handle separately
        trades = data.pop("trades", [])
        report = cls(**data)
        report.trades = trades
        return report

    # ── Factory from engine metrics ─────────────────────────────────

    @classmethod
    def from_metrics(
        cls,
        metrics: dict[str, Any],
        trades: list | None = None,
        *,
        strategy_id: str,
        strategy_name: str,
        context: str,
        total_markets: int = 0,
        date_range_start: str = "",
        date_range_end: str = "",
        config: dict | None = None,
        ranking_score: float = 0.0,
    ) -> StrategyReport:
        """Build a report from an ``engine.compute_metrics()`` dict.

        This is the primary factory for backtest reports.  The trading side
        uses a similar factory in ``trading.report``.
        """
        trade_records = []
        if trades:
            for t in trades:
                # Handle both Trade dataclass objects and dicts
                if hasattr(t, "market_id"):
                    trade_records.append(
                        {
                            "market_id": t.market_id,
                            "direction": t.direction,
                            "entry_price": t.entry_price,
                            "exit_price": t.exit_price,
                            "outcome": t.outcome,
                            "pnl": t.pnl,
                            "second_entered": t.second_entered,
                            "asset": t.asset,
                            "duration_minutes": t.duration_minutes,
                            "exit_reason": t.exit_reason,
                            "gross_pnl": t.gross_pnl,
                            "entry_fee_usdc": t.entry_fee_usdc,
                            "exit_fee_usdc": t.exit_fee_usdc,
                            "net_shares": t.net_shares,
                        }
                    )
                elif isinstance(t, dict):
                    trade_records.append(t)

        return cls(
            strategy_id=strategy_id,
            strategy_name=strategy_name,
            context=context,
            total_markets_evaluated=total_markets,
            skipped_markets_missing_features=metrics.get(
                "skipped_markets_missing_features", 0
            ),
            date_range_start=date_range_start,
            date_range_end=date_range_end,
            total_bets=metrics.get("total_bets", 0),
            wins=metrics.get("wins", 0),
            losses=metrics.get("losses", 0),
            win_rate_pct=metrics.get("win_rate_pct", 0.0),
            total_pnl=metrics.get("total_pnl", 0.0),
            avg_bet_pnl=metrics.get("avg_bet_pnl", 0.0),
            profit_factor=metrics.get("profit_factor", 0.0),
            expected_value=metrics.get("expected_value", 0.0),
            total_entry_fees=metrics.get("total_entry_fees", 0.0),
            total_exit_fees=metrics.get("total_exit_fees", 0.0),
            total_fees=metrics.get("total_fees", 0.0),
            sharpe_ratio=metrics.get("sharpe_ratio", 0.0),
            sortino_ratio=metrics.get("sortino_ratio", 0.0),
            max_drawdown=metrics.get("max_drawdown", 0.0),
            std_dev_pnl=metrics.get("std_dev_pnl", 0.0),
            pct_profitable_assets=metrics.get("pct_profitable_assets", 0.0),
            pct_profitable_durations=metrics.get(
                "pct_profitable_durations", 0.0
            ),
            consistency_score=metrics.get("consistency_score", 0.0),
            q1_pnl=metrics.get("q1_pnl", 0.0),
            q2_pnl=metrics.get("q2_pnl", 0.0),
            q3_pnl=metrics.get("q3_pnl", 0.0),
            q4_pnl=metrics.get("q4_pnl", 0.0),
            ranking_score=ranking_score,
            trades=trade_records,
            config=config or {},
        )
